sudo: required 
services:
  - docker
# ref: https://docs.travis-ci.com/user/languages/python
language: python
python:
  - "3.6"


before_install:
  - docker version
  - docker info
install:
    - npm install newman
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install nose
    - pip install Flask-Testing
before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version  
    
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json

after_success:
  - docker login -u XguetCHdh9G/uLPHpRS1GXcBE/PoHu+Ec6hBh50MaPT9kRR6/8C+7zZ1PwN+PdJXbadBXcWJboWAQMSDSq/+Dej+mY1hGp4ah5s3deyMU+UToPB/BLbA7rhm9abg0gSczBOU08KANDLaXpnYX+Lq2tSV80SSNBWCBwqg2+LhMCY8wuDYhb7QRnee7qdk3js+RTgTfGETHMYz8RiJb5cStObFUtAmFXd2kCnkoYnj5ZdomEukQvsY2hyzF9qY5AYbQFfZfm1bGBeAcXWdVBLvNG8Rx21KPdMIjThl7nh8B79NZq20dZhU100lGwokxf9tc1N90oufrCdLa66Hwh83NxWQ4EsgEU9Vqb59uDeVNkr2qP+vEauf+ysbDpYKcPW56XXIBum5ikM5sKqtaO+u7cgCvyUHvpKr1UtMrRaMdS3wR8DObZX7YtEHB4wpWiNeoVeUM59x4WPY/knoba2X3rLgRb0mfMwjVy5eGLVdQim9HjiwjWNT3lqzhRq7ZPKIvKrIb2ZRt1RFngA8MYP3a7yduh8czhmiDsumpgsQu2NQ2Qj5UYEAP3+n47SVEgA7HkQy7U2R8OVm9mG8A+XqUZikS0g2kaCAXAtoMjRbAoCoQEuFeBgtno1yZLRtX7f/Q9i2HlYX1D5EwwoKe7mY9ea5zp0TyJJSpC/MeV2mPFI= -p NqYgVYDAlkBH0RmD5gRuV0jUVyBWSw3mJ0BcoyDNzDlBfKDenbwt3vgkQzqj0EIwSFhQMPPPqzmdcrYvuYb4DF2IMM1yQJ6zULr2IYxTv6FJt93gjRt6VUmHY8j+KTJDU/i+treJqBPa41UKtfSaSljlRsZEmqxJSa1Fs7xOUU6VU61Aey0F9fQlRMkJGij8VBNtmvRJ4DleByRx5TsntSSETGPjcahJW1fv6OkvymhKU1kPXdMXfxoRuevfeYR1dWeuIXCFoFrNtGIdpZZz1p0LNgHiOw8pKh49/vXrasheIgN4x2Jio4X5o4RLUkhhhrj+IdZav5H6+cgNNIc8VvP7sAXEWJue8CQ6104SndXIyE/P6GFCElZ5zQAUcuYdSu9V1pXhC4gQEpcmIF/1KEumfTLMznvn6ap4jxwCUm7x5FU3OLnTDYgOHmQS9BTCcB0Bu4AdXiiNWPCU3TgVVZCUUfpAnEldXnPisoIZdM35rEQvXP07ZUsnslTiXDqIYwaxPTfSp+IB2f1mpyTYtRY9dA+tp3aMUoNjGjpVi7HFHaiOqFwCTxRT+gLM6liRDleg/QwABfRPQ3ygk2b+yvArZUk2ggk2YlGhqJHiVNR41u3VUi0lBWkyu2KNDH2cwnQWuu5dWw0wFNePZ9qAf75KfGEqdYqD2D2BN/TkSzw=
  - docker tag my_docker_reposetory/swagger_server my_docker_reposetory/swagger_server
  - docker push my_docker_reposetory/swagger_server

env:
  gloval:
    secure: 
    secure: 